name: testconfigwanlin
spec:
    listeners:
    - name: listener_0
      address: 0.0.0.0
      port: 9000
      routes:
      - name: test_RouteConfiguration
        prefix: /
        clusters: 
        - wanlin_test_cluster
    clusters:
    - name: wanlin_test_cluster
      endpoints:
      - address: www.envoyproxy.io
        port: 443